### ISSUE TITLE
The program doesn't start

### ISSUE THREAD

**Issue by LuSP19** [drgerg/mmc4w#16]
```
Traceback (most recent call last):
  File "mmc4w.py", line 1777, in <module>
  File "mmc4w.py", line 930, in plupdate
IndexError: list index out of range
```

The cpl is empty and `cpl[0]` gives an error.

**Comment by drgerg** [comment]
OK.  I'm wrapping up another release, and I'll see if I can solve this one before I put it up here.
Thanks.

**Comment by drgerg** [comment]
I was able to replicate the error by deleting all the saved playlists from one of my MPD servers.  So that was the cause.  Now I can make a fix.
Thanks!
