### ISSUE TITLE
Program can't find the cover.png file

### ISSUE THREAD

**Issue by LuSP19** [drgerg/mmc4w#17]
```
Traceback (most recent call last):
  File "mmc4w.py", line 1784, in <module>
  File "mmc4w.py", line 1572, in artWindow
  File "PIL\Image.py", line 3236, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Programs\\MMC4W\\_internal\\cover.png'
```

Copying the file to the _internal directory solves the problem. Seems like the installer is not installing this file.

**Comment by drgerg** [comment]
Ha!  You are right.  This one's pretty easy.  I'm on it.

**Comment by LuSP19** [comment]
Looks like I've encountered another problem with the program. )
Trying to find out the reason...

**Comment by drgerg** [comment]
I'm curious, are you starting fresh with an MPD server that has never yet played a song?  This could be a reason.  MMC4W has never (until now) been tested on a brand new server.  I'm testing it now, though.  ;-)

**Comment by LuSP19** [comment]
> I'm curious, are you starting fresh with an MPD server that has never yet played a song? This could be a reason. MMC4W has never (until now) been tested on a brand new server. I'm testing it now, though. ;-)

Today I'm launching the MPD for the first time. I wanted to find a multi-platform solution with a normal database and custom tags (MPD seems to support them through so-called stickers, although clients almost do not support them).
But the MPD documentation is quite bad and all clients have some problems. I may have to use something else... )

**Comment by drgerg** [comment]
I will agree that MPD is somewhat of a beast.  I only change the very minimum of settings in the config file.  MPC is a command line app that I use for worst-case control of MPD.  'mpc help' get you command help.  It works.

MMC4W was written by me for me.  I don't use tags, and don't really understand them, so MMC4W isn't likely to support them.  
Thanks to you, however, I did set up a server with no playlists and a clear queue, and was able to make a couple of tweaks.  I appreciate you taking the time to open the issue.

**Comment by LuSP19** [comment]
Thank you for sharing the code. Now someone can fork it and try to add support for stickers. Although I have had a bad experience with Tkinter in conjunction with threads, maybe I'll give it another try.

**Comment by drgerg** [comment]
I'm not real fond of Tkinter, but it is functional, and here at my house this app just runs all day long with not hiccups.  So I don't have any reason to want to do anything else.

Thanks for your kind comments.  They were helpful.

**Comment by drgerg** [comment]
You may want to hold off forking it until I put v2.0.9 up later today.  I think I've made some worthwhile improvements.  And the stuff you and I did today will be in there.

**Comment by drgerg** [comment]
The missing cover.png file is corrected.  I'm marking this closed.
