### ISSUE TITLE
Unhandled Exceptipon in getcurrsong

### ISSUE THREAD

**Issue by chillicao** [drgerg/mmc4w#22]
Using mmc4w from the setup.
Tested on an MPD that has only mp3/ogg streams in its playlist and got an error getting "KeyError 'duration'" which seems to be because streams have no duration, or 00:00 ?
Changed to an MPD that contains just 1 mp3 track in a loop and got this error instead:

The Unhandled exception in script shows up:
Failed to execute script 'mmc4w' due to unhandled exception: 'track'
Traceback (most recent call last):
  File "mmc4w.py", line 1922, in <module>
  File "mmc4w.py", line 776, in getcurrsong
  File "mmc4w.py", line 835, in getendtime
KeyError: 'track'

Last line in the mmc4w.log is:
Mon, 27 May 2024 09:45:54 -  = = = = = = getcurrsong = = = = = = = = 

Enabled debug output and mmc4w_DEBUG.log shows:
Mon, 27 May 2024 09:46:46 -  
Mon, 27 May 2024 09:46:46 -      -----======<<<<  STARTING UP  >>>>======-----
Mon, 27 May 2024 09:46:46 - D0) sys.platform is win32
Mon, 27 May 2024 09:46:46 -  
Mon, 27 May 2024 09:46:46 - D1| Initial errvar: Not connected
Mon, 27 May 2024 09:46:46 - D1| Try to reconnect to 10.1.3.201 on port 6632
Mon, 27 May 2024 09:46:46 - D1| 2nd try. cxstat is : 1
Mon, 27 May 2024 09:46:46 - ---=== Start songtitlefollower() threaded timer. ===---
Mon, 27 May 2024 09:46:46 -  
Mon, 27 May 2024 09:46:46 - STREAM b'IHDR' 16 13
Mon, 27 May 2024 09:46:46 - STREAM b'iCCP' 41 389
Mon, 27 May 2024 09:46:46 - iCCP profile name b'ICC profile'
Mon, 27 May 2024 09:46:46 - Compression method 0
Mon, 27 May 2024 09:46:46 - STREAM b'bKGD' 442 6
Mon, 27 May 2024 09:46:46 - b'bKGD' 442 6 (unknown)
Mon, 27 May 2024 09:46:46 - STREAM b'pHYs' 460 9
Mon, 27 May 2024 09:46:46 - STREAM b'tIME' 481 7
Mon, 27 May 2024 09:46:46 - b'tIME' 481 7 (unknown)
Mon, 27 May 2024 09:46:46 - STREAM b'tEXt' 500 25
Mon, 27 May 2024 09:46:46 - STREAM b'IDAT' 537 6518
Mon, 27 May 2024 09:46:46 -  = = = = = = getcurrsong = = = = = = = = 
Mon, 27 May 2024 09:46:46 - D2| Sent: 0
Mon, 27 May 2024 09:46:46 - D2| Got status. state: play, rand: r, rpt: P.
Mon, 27 May 2024 09:46:46 - D2| Retrieving "cs" in getcurrsong().
Mon, 27 May 2024 09:46:46 - D2| Got cs (client.currentsong()) with a length of 7.

Switched back to the MPD with the stream playlist (which none can output a 'duration'):
Traceback (most recent call last):
  File "mmc4w.py", line 1922, in <module>
  File "mmc4w.py", line 776, in getcurrsong
  File "mmc4w.py", line 834, in getendtime
KeyError: 'duration'

debug .log is the same, only last line is:
Mon, 27 May 2024 09:54:04 - D2| Got cs (client.currentsong()) with a length of 5.

Perhaps some sanity checks needed in getcurrsong ?

**Comment by drgerg** [comment]
Yes, that is a brand new use-case for MMC4W in my experience.  Using it with a server configured this way is going to be a wasted effort.  The entire design of this client depends on knowing the duration of the current playing song.  Without that bit of information, it cannot determine when to come back to the server for information about the next song as it starts playing.

This is not surprising.  It just means this client won't work in any scenario where the server doesn't provide "duration" when polled for current song status.

I would call this issue a design limitation.  Without knowing the duration of the current song, MMC4W is driving in the dark.

After I had done most of the work on this app, I learned there is a mechanism whereby the client puts itself in what I understand as a "wait state" keeping the socket open.  Then when something changes on the server, like a new song starts, the server 'finishes the conversation' and gives the client what it was waiting to hear.

That system of communication between server and client is more likely to work in the type of setup you are describing.  It is not something MMC4W will ever use. 

So, unfortunately I am not going to be able to address getting MMC4W to work in situations where the server does not provide a "duration" value for the currently playing song. 

Sorry!

**Comment by drgerg** [comment]
Yeah, it's like the idle thing.  I never knew it existed until after I'd built MMC4W to work without it.  

To answer your question: If a server you select isn't running, MMC4W will error out and exit.  If it is running, MMC4W asks it what its status is.  If the server is in a 'stop' or 'pause' state, MMC4W just adopts that state in its interface.  If it's a 'pause' state, there will be a song title and duration and elapsed values.  MMC4W calculates and end time from that and checks back to see if anything changed when that time passes.
If it's a 'stop' status, nothing at all will happen until a button is pressed.  It is assumed the user can hear that the server is not playing, so it's natural to also assume they will press the play button.  Of course, who knows what people will do or why?

I do need to clean things up a bit to better handle the server just being absent when you start up.  MMC4W could be a bit more graceful in letting you know about that.

**Comment by chillicao** [comment]
I think the problem with the 'track' error is that my mp3 file on mpd has no track # tag? if that's the case yes, it should be more graceful really!

**Comment by drgerg** [comment]
#!/usr/bin/env python3
# 
# mmc4w_diag.py - 2024 by Gregory A. Sanders (dr.gerg@drgerg.com)
# Minimal MPD Client for Windows Diagnostics Tool
# mmc4w_diag.py uses the python-musicpd library.
##

import sys
from configparser import ConfigParser
import os
import musicpd
from pathlib import Path

if sys.platform != "win32":
    import subprocess
else:
    # from win32api import GetSystemMetrics
    import ctypes
    ctypes.windll.shcore.SetProcessDpiAwareness(0)
    ctypes.windll.user32.SetProcessDPIAware()

version = "v0.0.1"

client = musicpd.MPDClient()                    # create client object

# confparse is for general use for normal text strings.
# confparse = ConfigParser()
confparse = ConfigParser()

# cp is for use where lists are involved.
cp = ConfigParser(converters={'list': lambda x: [i.strip() for i in x.split(',')]})

# path_to_dat = path.abspath(path.dirname(__file__))
path_to_dat = Path(__file__).parent
mmc4wIni = path_to_dat / "mmc4w_diag.ini"
workDir = os.path.expanduser("~")
confparse.read(mmc4wIni)
serverlist = confparse.get('basic','serverlist')
serverip = confparse.get('serverstats', 'lastsrvr')
serverport = confparse.get('basic','serverport')

client.connect(serverip, int(serverport))

cs = []
stat = []
stat = client.status()
cs = client.currentsong()
print("\nOUTPUT OF CLIENT.STATUS():\n {}\n".format(stat))
print("\nOUTPUT OF CLIENT.CURRENTSONG():\n {}\n".format(cs))

**Comment by drgerg** [comment]
I did up this quick little utility that shows the contents of the two most used responses from the MPD server: "status" and "currentsong".  Let's see if we can get it to you intact.  I think it should be here below:

```
#!/usr/bin/env python3
# 
# mmc4w_diag.py - 2024 by Gregory A. Sanders (dr.gerg@drgerg.com)
# Minimal MPD Client for Windows Diagnostics Tool
# mmc4w_diag.py uses the python-musicpd library.
##

import sys
from configparser import ConfigParser
import os
import musicpd
from pathlib import Path

if sys.platform != "win32":
    import subprocess
else:
    # from win32api import GetSystemMetrics
    import ctypes
    ctypes.windll.shcore.SetProcessDpiAwareness(0)
    ctypes.windll.user32.SetProcessDPIAware()

version = "v0.0.1"

client = musicpd.MPDClient()                    # create client object

# confparse is for general use for normal text strings.
# confparse = ConfigParser()
confparse = ConfigParser()

# cp is for use where lists are involved.
cp = ConfigParser(converters={'list': lambda x: [i.strip() for i in x.split(',')]})

# path_to_dat = path.abspath(path.dirname(__file__))
path_to_dat = Path(__file__).parent
mmc4wIni = path_to_dat / "mmc4w_diag.ini"
workDir = os.path.expanduser("~")
confparse.read(mmc4wIni)
serverlist = confparse.get('basic','serverlist')
serverip = confparse.get('serverstats', 'lastsrvr')
serverport = confparse.get('basic','serverport')

client.connect(serverip, int(serverport))

cs = []
stat = []
stat = client.status()
cs = client.currentsong()
print("\nOUTPUT OF CLIENT.STATUS():\n {}\n".format(stat))
print("\nOUTPUT OF CLIENT.CURRENTSONG():\n {}\n".format(cs))
```

**Comment by drgerg** [comment]
I have that file named mmc4w_diag.py on my system.

Here is the second file:  mmc4w_diag.ini:
```
[basic]
serverlist = 192.168.1.22,192.168.1.16,192.168.1.28
serverport = 6600

[program]
version = v0.0.1

[serverstats]
lastsrvr = 192.168.1.22
lastport = 6600
```

**Comment by drgerg** [comment]
If you get those saved somewhere, and if you install the dependencies, you can run mmc4w_diag.py in a terminal and get a look at the data returned.  Like this:

```PS C:\Users\Greg\mydrive\Projects\Python\Python in Windows\MMC4W> python .\mmc4w_diag.py

OUTPUT OF CLIENT.STATUS():
 {'volume': '40', 'repeat': '0', 'random': '1', 'single': '0', 'consume': '1', 'partition': 'default', 'playlist': '93', 'playlistlength': '700', 'mixrampdb': '0', 'state': 'stop', 'song': '322', 'songid': '1054', 'nextsong': '696', 'nextsongid': '1433'}


OUTPUT OF CLIENT.CURRENTSONG():
 {'file': 'U2/The Best of U2 - 1990-2000/13-Hold Me, Thrill Me, Kiss Me, Kill Me.flac', 'last-modified': '2023-12-18T23:22:48Z', 'format': '44100:16:2', 'title': 'Hold Me, Thrill Me, Kiss Me, Kill Me', 'artist': 'U2', 'album': 'The Best of U2 - 1990-2000', 'genre': 'Rock', 'track': '13', 'date': '2002', 'time': '285', 'duration': '285.160', 'pos': '322', 'id': '1054'}
```

**Comment by drgerg** [comment]
Those last dictionaries (python dictionary) were from the server in a 'stopped' state.  Here's what you get when it's running:
```
PS C:\Users\Greg\mydrive\Projects\Python\Python in Windows\MMC4W> python .\mmc4w_diag.py

OUTPUT OF CLIENT.STATUS():
 {'volume': '40', 'repeat': '0', 'random': '1', 'single': '0', 'consume': '1', 'partition': 'default', 'playlist': '93', 'playlistlength': '700', 'mixrampdb': '0', 'state': 'play', 'song': '322', 'songid': '1054', 'time': '7:285', 'elapsed': '7.026', 'bitrate': '1081', 'duration': '285.160', 'audio': '44100:16:2', 'nextsong': '696', 'nextsongid': '1433'}


OUTPUT OF CLIENT.CURRENTSONG():
 {'file': 'U2/The Best of U2 - 1990-2000/13-Hold Me, Thrill Me, Kiss Me, Kill Me.flac', 'last-modified': '2023-12-18T23:22:48Z', 'format': '44100:16:2', 'title': 'Hold Me, Thrill Me, Kiss Me, Kill Me', 'artist': 'U2', 'album': 'The Best of U2 - 1990-2000', 'genre': 'Rock', 'track': '13', 'date': '2002', 'time': '285', 'duration': '285.160', 'pos': '322', 'id': '1054'}
```

**Comment by drgerg** [comment]
So armed with that data, you have a better chance to see what's going on.  Maybe that helps, maybe not.  ¯\_(ツ)_/¯

**Comment by chillicao** [comment]
yes, no tags, some of my other files are .wav and won't accept any tags

(base) C:\Users\p\AppData\Local\Programs\MMC4W>python mmc4w_diag.py

OUTPUT OF CLIENT.STATUS():
 {'repeat': '1', 'random': '0', 'single': '0', 'consume': '0', 'playlist': '3', 'playlistlength': '108', 'mixrampdb': '0.000000', 'state': 'pause', 'song': '71', 'songid': '72', 'time': '3:5411', 'elapsed': '2.504', 'bitrate': '256', 'duration': '5411.160', 'audio': '44100:24:2', 'nextsong': '72', 'nextsongid': '73'}


OUTPUT OF CLIENT.CURRENTSONG():
 {'file': 'mixc.2021-01-18.070000.Monday.m4a.mp3', 'last-modified': '2024-02-08T21:55:35Z', 'artist': 'music2', 'title': 'mixc.2021-01-18.070000.Monday.m4a.mp3', 'genre': 'Blues', 'time': '5411', 'duration': '5411.160', 'pos': '71', 'id': '72'}

**Comment by drgerg** [comment]
Well there you go!  Get your library in decent order and everything will be better.  

I messed around with a lot of different codecs before settling on FLAC.  I've never regretted the decision.

Best of luck to you!

**Comment by chillicao** [comment]
Thank you for fixing this issue in your software by letting users know that it only works if their files are tagged.
